### ISSUE TITLE
Missing legal moves

### ISSUE THREAD

**Issue by SwissKid** [malbrecht/chess#1]
FEN layout:
r1bqkbnr/1ppp1ppp/p1B5/4p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 0 4

Move:
D7 to C6

This is a legal move, but isn't in the list of "Legal Moves"

**Comment by SwissKid** [comment]
Funny - parsemove would let it in, but it's not in the Legal Moves list

**Comment by malbrecht** [comment]
Thanks for the report. The LegalMoves list was messed up, some moves missing, some duplicated. ParseMove worked because it uses the underlying pseudoLegalMoves directly.
